spring:
  jpa:
    hibernate:
      ddl-auto: update # 设置数据库模式更新策略
    open-in-view: false
  application:
    name: bs-tier
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/contact?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8088